- name: Copy test files over
  copy: src=sandbox/without_year/ dest="{{ test_directory.stdout }}"

- name: Pre explicit year add stat
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" stat
  register: stat_prestat_call 

- name: Stat has missing at start of unparseable tests
  assert: 
        that: 
        - "'? Test File Two.docx' in stat_prestat_call.stdout"
        - "'? Test File Tres.docx' in stat_prestat_call.stdout"
        - "'? test4.doc' in stat_prestat_call.stdout"
        - "'? test5.txt' in stat_prestat_call.stdout"
        - "'? 1984.test6.txt' in stat_prestat_call.stdout"
        - "'? 1985.test7.txt' in stat_prestat_call.stdout"

- name: Attempt to add a non parseable name without year - should fail. 
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" add test4.doc
  ignore_errors: True
  register: bad_parse_fail

- name: debug incorrectly successful add call
  debug: var=bad_parse_fail
  when: bad_parse_fail|success 

- name: Add should not have a good rc on failure
  assert:
        that:
        - "bad_parse_fail|failed"

- name: Stat after parse add failure
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" stat
  register: stat_parse1_call 

- name: Stat has missing non-parseable file 
  assert: 
        that: 
        - "'? Test File Tres.docx' in stat_parse1_call.stdout"
        - "'? Test File Two.docx' in stat_parse1_call.stdout"
        - "'? test4.doc' in stat_parse1_call.stdout"
        - "'? test5.txt' in stat_parse1_call.stdout"
        - "'? 1984.test6.txt' in stat_parse1_call.stdout"
        - "'? 1985.test7.txt' in stat_parse1_call.stdout"

- name: Add with year 
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" add --year 1944 test4.doc

- name: Stat after year add success
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" stat
  register: stat_yearadd_call 

- name: Stat has still missing files 
  assert: 
        that: 
        - "'? Test File Tres.docx' in stat_yearadd_call.stdout"
        - "'? Test File Two.docx' in stat_yearadd_call.stdout"
        - "'? test5.txt' in stat_yearadd_call.stdout"
        - "'? 1984.test6.txt' in stat_yearadd_call.stdout"
        - "'? 1985.test7.txt' in stat_yearadd_call.stdout"

- name: Stat does not have added by year
  fail: msg="File is not in index '{{ stat_yearadd_call.stdout }}'"
  when: '"? test4.doc" in stat_yearadd_call.stdout'


- name: Add multiple without year
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" add test5.txt 1984.test6.txt
  ignore_errors: True
  register: multi_wo_year 
  
- name: debug incorrectly successful add call
  debug: var=multi_wo_year
  when: multi_wo_year|success 

- name: Should have failed as 1 is missing year 
  assert:
        that:
        - "multi_wo_year|failed"

- name: Stat after multiple year add failure
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" stat
  register: stat_multiple_wo_year

- name: Stat has missing non parseable file 
  assert: 
        that: 
        - "'? test5.txt' in stat_multiple_wo_year.stdout"

- name: Stat does not have file that had year 
  fail: msg="File is not in index '{{ stat_multiple_wo_year.stdout }}'"
  when: '"? 1984.test6.txt" in stat_multiple_wo_year.stdout'

- name: Add multiple with year
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" add --year 1978 test5.txt 1985.test7.txt
  register: multi_w_year 

- name: Stat after multiple year add success
  command: chdir="{{ test_directory.stdout }}" "{{ kay_app.stdout }}" stat
  register: stat_multiple_w_year

- name: Stat does not have files added 
  fail: msg="test5.txt is not in index '{{ stat_multiple_w_year.stdout }}'"
  when: '"? test5.txt" in stat_multiple_w_year.stdout'

- name: Stat does not have files added 
  fail: msg="1985.test7.txt is not in index '{{ stat_multiple_w_year.stdout }}'"
  when: '"? 1985.test7.txt" in stat_multiple_w_year.stdout'
