- name: build the install directory
  command: mktemp -dt kay_test_install
  register: install_directory

- name: set bash sources to the tmp install directory
  command: echo "{{ install_directory.stdout }}"
  register: bash_sources

- name: build the test directory
  command: mktemp -dt kay_test
  register: test_directory

